### ISSUE TITLE
Only rebase one PR per time

### ISSUE THREAD

**Issue by LinqLover** [bbeesley/gha-auto-dependabot-rebase#28]
For my master branch, I have enabled the option "Require branches to be up to date before merging". This means that rebasing multiple PRs upon push would raise the CI complexity from O(n) to O(n²). Would it be possible to provide an option to only rebase one PR at a time, e.g., the oldest one?

**Comment by melink14** [comment]
Should this be reopened since the fix was rolled back? Not sure how difficult it is to avoid the json parse errors but hopefully it's a small change.
